const Fonts = {
    get mono() { return this.iosevka},
    Iosevka: {
        thin: { name: 'iosevka-thin', weight: 100, style: 'normal' },
        thinitalic: { name: 'iosevka-thinitalic', weight: 100, style: 'italic' },
        thinoblique: { name: 'iosevka-thinoblique', weight: 100, style: 'oblique' },
        extralight: { name: 'iosevka-extralight', weight: 200, style: 'normal' },
        extralightitalic: { name: 'extralightitalic', weight: 200, style: 'italic' },
        extralightoblique: { name: 'iosevka-extralightoblique', weight: 200, style: 'oblique' },
        light: { name: 'iosevka-light', weight: 300, style: 'normal' },
        lightitalic: { name: 'iosevka-lightitalic', weight: 300, style: 'italic' },
        lightoblique: { name: 'iosevka-lightoblique', weight: 300, style: 'oblique' },
        regular: { name: 'iosevka-regular', weight: 400, style: 'normal' },
        italic: { name: 'iosevka-italic', weight: 400, style: 'italic' },
        oblique: { name: 'iosevka-oblique', weight: 400, style: 'oblique' },
        medium: { name: 'iosevka-medium', weight: 500, style: 'normal' },
        mediumitalic: { name: 'iosevka-mediumitalic', weight: 500, style: 'italic' },
        mediumoblique: { name: 'iosevka-mediumoblique', weight: 500, style: 'oblique' },
        semibold: { name: 'iosevka-semibold', weight: 600, style: 'normal' },
        semibolditalic: { name: 'iosevka-semibolditalic', weight: 600, style: 'italic' },
        semiboldoblique: { name: 'iosevka-semiboldoblique', weight: 600, style: 'oblique' },
        bold: { name: 'iosevka-bold', weight: 700, style: 'normal' },
        bolditalic: { name: 'iosevka-bolditalic', weight: 700, style: 'italic' },
        boldoblique: { name: 'iosevka-boldoblique', weight: 700, style: 'oblique' },
        extrabold: { name: 'iosevka-extrabold', weight: 800, style: 'normal' },
        extrabolditalic: { name: 'iosevka-extrabolditalic', weight: 800, style: 'italic' },
        extraboldoblique: { name: 'iosevka-extraboldoblique', weight: 800, style: 'oblique' },
        heavy: { name: 'iosevka-heavy', weight: 900, style: 'normal' },
        heavyitalic: { name: 'iosevka-heavyitalic', weight: 900, style: 'italic' },
        heavyoblique: { name: 'iosevka-heavyoblique', weight: 900, style: 'oblique' },
    },
}
export default Fonts
